---
- hosts: raspi
  tasks:
  - name: install prerequisites for Docker repository
    become: yes
    ansible.builtin.apt:
      pkg:
        - ca-certificates
        - curl
        - gnupg2
        - lsb-release

  - name: add docker apt key
    become: yes
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker apt repo
    become: yes
    apt_repository:
      repo: "deb [arch=arm64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
      state: present
      update_cache: yes

  - name: create Docker config folder
    become: yes
    file:
      path: /etc/docker
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: install docker and its dependencies
    become: yes
    apt:
      pkg:
        - docker-ce
        - python3-docker
        - docker-compose
      state: present
      update_cache: true
    retries: 3
    register: result
    until: result is not failed
