all:
  hosts:
    raspi:
      ansible_host: localhost
      ansible_connection: local
      ansible_python_interpreter: "{{ansible_playbook_python}}"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
