all:
  hosts:
    local:
      ansible_host: localhost
    init:
      ansible_host: localhost
      ansible_port: 2222
      ansible_ssh_user: pi
      ansible_ssh_pass: raspberry
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    raspi:
      ansible_host: localhost
      ansible_port: 2222
      ansible_ssh_user: "{{ account.username }}"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
