---
- hosts: raspi
  gather_facts: no

  tasks:
  - name: add user account
    become: true
    user:
      name: "{{ account.username }}"
      password: "{{ account.password }}"

  - name: add user to sudoers
    become: true
    community.general.sudoers:
      name: $USERS
      state: present
      user: "{{ account.username }}"
      commands: ALL
