---
- hosts: raspi
  gather_facts: no

  tasks:
  - name: add user account
    become: true
    user:
      name: "{{ account.username }}"
      password: "{{ account.password }}"

  - name: add user to sudoers
    become: true
    community.general.sudoers:
      name: $USERS
      state: present
      user: "{{ account.username }}"
      commands: ALL

  - name: disable root login over SSH
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin yes'
      line: 'PermitRootLogin prohibit-password'
      state: present
  
  - name: disable empty passwords over SSH
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitEmptyPasswords yes'
      line: 'PermitEmptyPasswords no'
      state: present
