---
- hosts: raspi
  gather_facts: no
  tasks:
  - name: synchronize this template repo with raspi
    become: true
    synchronize:
      src: "{{ host.main_dir }}"
      dest: "{{ template.dir }}"
      delete: true
      recursive: true
      rsync_opts:
        - "--exclude=dist"
