---
- hosts: raspi
  tasks:
  - name: Synchronize this template repo with raspi
    synchronize:
      src: "{{ host.main_dir }}"
      dest: "~/"
      delete: true
      recursive: true
      rsync_opts:
        - "--exclude=dist"
