---
- hosts: local
  connection: local
  gather_facts: no
  tasks:
  - name: Start raspi machine
    docker_container:
      name: raspi
      image: ptrsr/pi-ci
      command: start
      state: started
      tls_hostname: localhost
      published_ports:
        - 2222:2222
      volumes:
        - "{{ dist_dir|default(omit) }}:/dist"

- hosts: raspi
  gather_facts: no
  tasks:
  - name: Wait for machine startup
    wait_for_connection:
      timeout: 300
