---
- hosts: local
  connection: local
  gather_facts: no
  vars:
    skip: false

  tasks:
  - name: start raspi machine
    docker_container:
      name: raspi
      image: ptrsr/pi-ci
      command: start
      state: started
      tls_hostname: localhost
      published_ports:
        - 2222:2222
      volumes:
        - "{{ host.dist_dir|default(omit) }}:/dist"
    register: startup

- hosts: raspi
  gather_facts: no
  tasks:
  - name: wait for machine startup
    wait_for_connection:
      timeout: 600
