name: PI-TEMPLATE
on: [push]

env:
  PI_CI: ptrsr/pi-ci:0.7

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Load Docker image
        run: docker pull $PI_CI

      - name: Install dependencies
        run: pip3 install docker-py

      - name: Configure image
        run: |
          ansible-playbook \
          -i inv/ci.yml \
          src/ci.yml

      - name: Export image
        run: |
          docker run -i --rm \
          -v $GITHUB_WORKSPACE/dist/:/dist \
          $PI_CI export -o /dist/distro.img

      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: distro
          path: dist/distro.img
